openapi: 3.0.1
info:
  contact:
    email: g2_family_lock@gmail.com
    name: G2 - Family Lock
    url: https://s-computing.blogspot.com/2020/09/familylock.html
  description: This API provides the neccesary data for the Family Lock project
  title: Family Lock API
  version: "1.0"
paths:
  /device_MAC:
    get:
      description: Return all the MAC devices
      operationId: getDeviceMAC
      parameters:
        - in: query
          name: DeviceMAC
          description: Device MAC
          schema:
            type: string
      responses:
        200:
          content:
            text/plain:
              schema:
                example: OK
                title: OK
                type: string
            application/json:
              schema:
                example: OK
                title: OK
                type: string
          description: OK
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Return all the devices MACs
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
    post:
      description: Addition of a new device MAC
      operationId: postDeviceMAC
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/DeviceMAC'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Add a new Device MAC.
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
    delete:
      description: Delete the selected Device MAC.
      operationId: deleteDeviceMAC
      parameters:
      - description: Device MAC
        explode: true
        in: query
        name: type
        required: true
        schema:
          type: string
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Deleted
                title: Deleted
                type: string
          description: Deleted
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Delete the device MAC.
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
    put:
      description: Update a device MAC
      operationId: putDeviceMAC
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                person_id:
                  type: string
                old_MAC:
                  type: string
                new_MAC:
                  type: string
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Update a device MAC
      tags:
      - DeviceMAC
      x-swagger-router-controller: DeviceMAC
  schemas:
    AllowedPlacesType:
      example:
        MAC: ff:ff:ff:ff:ff:ff:ff
        name: FamilyLock
      properties:
        MAC:
          example: restaurant
          type: string
        name:
          example: Restaurant
          type: string
      type: object